README.md
Please approve, just for readme
=> Feature myprofile biacolo

backend/audioscholar/.gitignore, backend/audioscholar/pom.xml, backend/audioscholar/src/main/java/edu/cit/audioscholar/config/AppConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AudioController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/AudioMetadata.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/User.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioProcessingService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/NhostStorageService.java, backend/audioscholar/src/main/resources/application.properties
This pull request fixes Firebase errors and updates dependencies. It includes the following commits:
- "Firebase errors": This commit addresses Firebase errors in the code.
- "feat: Add AppConfig for RestTemplate configuration": This commit adds an `AppConfig` class for configuring `RestTemplate`.
- "feat: Update AudioMetadata to use Google Cloud Timestamp instead of Instant": This commit updates the `AudioMetadata` class to use Google Cloud Timestamp instead of Instant.
- "chore: Update dependencies and remove unused code": This commit updates dependencies and removes unused code.
=> Fix Firebase errors and update dependencies

frontend_mobile/AudioScholar/app/src/main/AndroidManifest.xml, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/AudioScholarApplication.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/service/RecordingService.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/recording/RecordingScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/recording/RecordingViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/upload/UploadScreen.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
This pull request adds a foreground service and notification channels for recording audio. It includes the necessary permissions and updates the application manifest to include the foreground service and microphone permissions. It also adds a new service for recording and updates the notification channels in the application class.
=> Add foreground service and notification channels for recording audio

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LocalRecordingsListScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LocalRecordingsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
Previously, error handling and error messages for file upload and network connection were not robust. This pull request improves the error handling and provides more informative error messages for various scenarios, such as failed file reading, empty file content, network connection issues, and server errors. This enhancement ensures a better user experience and easier troubleshooting.
=> Improve error handling and messages for file upload and network connection

backend/audioscholar/pom.xml, backend/audioscholar/src/main/java/edu/cit/audioscholar/config/AppConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/config/SecurityConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AudioController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/GeminiController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/exception/FirestoreInteractionException.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioProcessingService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/resources/application.properties
This pull request includes updates to the dependencies and configurations for backend security measures and performance optimization. It also adds a new exception class for Firestore interaction. The changes include adding a new dependency for cache management, updating the application configuration to enable caching, and making changes to the GeminiController and AppConfig classes. Additionally, the pull request includes updates to the application properties file for logging and configuration settings related to Firebase, NHOST, Google, and JWT.
=> Update dependencies and configurations for backend security measures and performance optimization

backend/audioscholar/pom.xml, backend/audioscholar/src/main/java/edu/cit/audioscholar/config/RabbitMQConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/exception/GlobalExceptionHandler.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/exception/InvalidAudioFileException.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/AudioMetadata.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/ProcessingStatus.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/Recording.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioProcessingService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/resources/application.properties
This pull request adds a new enum called `ProcessingStatus` for audio processing status. It also updates the dependencies and implements the feature for Audio Ingestion and Validation.
=> Add ProcessingStatus enum and update dependencies

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/service/RecordingService.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/about/AboutScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/RegistrationScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsUiState.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/EditProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
This pull request includes several changes. First, it implements the `isEditingTitle` and `editableTitle` properties in the `RecordingDetailsUiState` class. These properties are used to handle the editing of the recording title.
Second, it adds the `deleteLocalRecordings` function to the `AudioRepository` interface. This function allows for the deletion of multiple local recordings at once.
Third, it updates the color of the `bodySmall` style in the `RegistrationScreen` to match the color scheme of the app.
Finally, it passes additional parameters to the `AboutScreen` in the `MainActivity`. These parameters include the `drawerState` and `scope`, which are used for navigation and coroutines respectively.
These changes improve the functionality and user experience of the app.
=> Implement isEditingTitle and editableTitle properties, deleteLocalRecordings, and update color of bodySmall style

backend/audioscholar/src/main/java/edu/cit/audioscholar/config/SecurityConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AuthController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/UserController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/AuthResponse.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/FirebaseTokenRequest.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/LoginRequest.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/OAuth2LoginSuccessHandler.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/UserService.java, frontend_mobile/AudioScholar/app/build.gradle.kts, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/dto/AuthDtos.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/service/ApiService.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/NetworkModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/RegistrationViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/util/Resource.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
This pull request implements the User Login feature with integration to the backend server using Spring Boot and Firebase. It includes changes to add the necessary classes and dependencies for user login, such as `LoginRequest`, `AuthResponse`, and `FirebaseTokenRequest`. The changes also include modifications to the `ApiService` interface and the `AudioRepository` interface to support login functionality. Additionally, there are updates to the security configuration in the backend to allow login requests and verify Firebase ID tokens.
=> Implement User Login feature with backend integration

backend/audioscholar/src/main/java/edu/cit/audioscholar/config/SecurityConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AuthController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/resources/application.properties, frontend_mobile/AudioScholar/app/build.gradle.kts, frontend_mobile/AudioScholar/app/google-services.json, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/service/ApiService.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginViewModel.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
This pull request implements a feature for user login using Google OAuth 2.0 for mobile Kotlin integration with the backend Spring Boot. It includes changes to the ApiService and AudioRepository interfaces, as well as updates to the application's configuration files and dependencies. Additionally, a new method `verifyGoogleToken` is added to the `AudioRepositoryImpl` class to handle the verification of Google ID tokens on the backend.
=> feat: implemented a feature for user login google oauth 2.0 for mobile kotlin integration with backend springboot

frontend_mobile/AudioScholar/app/build.gradle.kts, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/NetworkModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/AudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/upload/UploadViewModel.kt, frontend_mobile/AudioScholar/build.gradle.kts, frontend_mobile/AudioScholar/gradle/libs.versions.toml
This pull request fixes issues related to the fallback mechanism for URL endpoints in the Spring Boot backend from mobile. The changes include updates to the build.gradle.kts file, modifications to the UploadViewModel class, updates to the versions of dependencies, changes to the plugins in the build.gradle file, and modifications to the AudioRepositoryImpl class. These changes aim to resolve the issues and improve the functionality of the application.
=> fix: Fix issues regarding fallback mechanism for url endpoints for springboot backend from mobile.

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/EditProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/EditProfileViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/settings/ChangePasswordScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/settings/ChangePasswordViewModel.kt
This pull request implements a feature for mobile Account Profile Management. It includes the addition of two new ViewModel classes: `UserProfileViewModel` and `EditProfileViewModel`. The `UserProfileViewModel` is responsible for loading and managing the user's profile data, including name and email. The `EditProfileViewModel` handles the editing and saving of the user's profile information, including first name, last name, username, and email. These changes provide the necessary functionality for users to view and edit their account profiles within the mobile app.
=> Implement Account Profile Management for Mobile App

backend/audioscholar/pom.xml, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AuthController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/UserProfileController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/ChangePasswordRequest.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/UpdateUserProfileRequest.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/UserProfileDto.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/UserService.java
This pull request implements the Account Profile Management feature in the Server API. It includes the necessary changes to the codebase, such as adding new classes and updating dependencies. The feature allows users to update their profile information, such as display name and password.
=> Implement Account Profile Management feature (Server API)

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/NetworkModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/RegistrationScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/RegistrationViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt
This pull request includes updates to the User Registration features, specifically related to the Email/Password functionality. The changes in the code address certain issues and improve the overall functionality of the User Registration process.
=> feat: updated some features from User Registration (Email/Password)

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/CoroutineScopesModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/LoginViewModel.kt
This pull request implements post-login data prefetching in the mobile application. It adds a new module for coroutine scopes and provides different dispatchers for different coroutines. It also adds a new function to trigger background profile prefetching in the application scope. The `LoginViewModel` now calls this function after successful login to fetch the user profile in the background. This improves the user experience by preloading data and reducing the time required to load the profile when needed.
=> feat: Implement Post-Login Data Prefetching in mobile

backend/audioscholar/src/main/java/edu/cit/audioscholar/service/UserService.java, frontend_mobile/AudioScholar/app/build.gradle.kts, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainViewModel.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
Previously, there was a bug where the image URL was not updated during profile updates. This pull request fixes that bug. Additionally, it includes the user's profile data in the main navigation bar, such as the user's name and email. This provides a more personalized experience for the user.
=> Fix bug and include profile data in main navigation bar

backend/audioscholar/src/main/java/edu/cit/audioscholar/config/SecurityConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/GeminiController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/UserController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/LoginRequest.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioProcessingService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioSummarizationListenerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/GeminiService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/LearningMaterialRecommenderService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/LectureContentAnalyzerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/OAuth2LoginSuccessHandler.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/TokenRevocationService.java
\`\`\`
This pull request refines the Gemini Prompt for Direct Summarization Output. It includes changes to the `LoginRequest` class, the `GeminiController` class, and the `LectureContentAnalyzerService` class. The changes in the `LoginRequest` class remove the `Size` validation constraint. In the `GeminiController` class, the `testGemini` method now handles error responses from the Gemini service. The `LectureContentAnalyzerService` class now retrieves topics from the stored summary and returns them in the analysis results.
=> Refine Gemini Prompt for Direct Summarization Output

backend/audioscholar/.vscode/settings.json, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/SummaryDto.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/Summary.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioSummarizationListenerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/GeminiService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/SummaryService.java
This pull request enhances the Summarization feature by adding glossary generation. It includes changes to the `SummaryDto` and `Summary` classes, adding a `glossary` field to both classes. The `SummaryDto` class now has a `getGlossary` method and the `Summary` class has a `getGlossary` and `setGlossary` method. The `Summary` class also includes changes to the `toMap` and `fromMap` methods to handle the glossary field. This enhancement improves the functionality of the Summarization feature by allowing the generation and retrieval of a glossary for each summary.
=> Enhance Summarization to Include Glossary Generation

backend/audioscholar/src/main/java/edu/cit/audioscholar/model/AudioMetadata.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/Recording.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioSummarizationListenerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/LearningMaterialRecommenderService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/RecordingService.java
This pull request includes changes to integrate Learning Recommendations and update the `audio_metadata` structure. The changes include refactoring the `getLearningRecommendationsByRecordingId` method, adding new fields to the `convertToMap` and `fromDocumentSnapshot` methods, and handling the audio processing request. The changes also include creating a prompt for the recording, handling the Gemini JSON response, and updating the metadata status.
=> Integrate Learning Recommendations and Update `audio_metadata` Structure

frontend_mobile/AudioScholar/.vscode/settings.json, frontend_mobile/AudioScholar/app/build.gradle.kts, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/dao/CloudCacheDao.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/dao/RecordingMetadataDao.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/db/AppDatabase.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/db/Converters.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/model/CloudCacheEntity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/model/RecordingMetadata.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/service/ApiService.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/DatabaseModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/RepositoryModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/CloudCacheRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/CloudCacheRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/LocalAudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/LocalAudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/RemoteAudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/RemoteAudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/service/PlaybackManager.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsUiState.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/recording/RecordingViewModel.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
- Added Room database setup with AppDatabase class.
- Created CloudCacheDao and RecordingMetadataDao interfaces for data access.
- Introduced CloudCacheEntity and RecordingMetadata data models.
- Implemented type converters for Gson serialization/deserialization.
- Updated dependencies in build.gradle.kts for Room.
- Added new methods for managing cloud cache and recording metadata.
- Enhanced RecordingDetailsScreen and ViewModel to support cloud recording details.
=> feat: Implement Room database and DAOs for cloud cache and recording metadata

backend/audioscholar/src/main/java/edu/cit/audioscholar/config/RabbitMQConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AudioController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/GeminiController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/SummaryController.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/dto/NhostUploadMessage.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/AudioMetadata.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/LearningRecommendation.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/ProcessingStatus.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/Summary.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioProcessingService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioSummarizationListenerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/GeminiService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/LearningMaterialRecommenderService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/NhostStorageService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/NhostUploadListenerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/RecordingService.java, backend/audioscholar/src/main/resources/application.properties, frontend_mobile/AudioScholar/app/build.gradle.kts, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/NetworkModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/RemoteAudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/RemoteAudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml, frontend_mobile/AudioScholar/settings.gradle.kts
This pull request includes improvements to the gemini summarize feature, notes output, and the visual display of recording details for mobile. The changes include adding a new dependency, updating an enum, modifying a remote audio repository, updating string resources, modifying application properties, adding a new DTO class, and updating the Gemini controller and RabbitMQ configuration. These changes aim to enhance the functionality and user experience of the application.
=> Improve gemini summarize, notes output and the visual display for the output of recording details for mobile

backend/audioscholar/src/main/java/edu/cit/audioscholar/service/UptimeRobotService.java
The UptimeRobotService class has been refactored to improve code readability and maintainability. The changes include reorganizing the code, removing unnecessary log statements, and adding proper error handling. This refactoring does not fix any specific issue but aims to enhance the overall quality of the code.
=> Refactor UptimeRobotService class

backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AuthController.java, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/local/model/RecordingMetadata.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/service/ApiService.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/RemoteAudioRepository.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/domain/repository/RemoteAudioRepositoryImpl.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/RegistrationScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/auth/RegistrationViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsUiState.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/EditProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
- Added a new API endpoint to delete cloud recording metadata.
- Enhanced error handling for deletion operations, including specific messages for forbidden access and not found errors.
- Updated UI components to reflect changes in cloud recording management.
- Improved logging for better traceability during deletion processes.
- Added new string resources for user feedback on deletion actions.
=> feat: Implement cloud recording deletion and improve error handling

frontend_web/audioscholar-app/index.html, frontend_web/audioscholar-app/src/App.jsx, frontend_web/audioscholar-app/src/components/GithubAuthCallback.jsx, frontend_web/audioscholar-app/src/components/HeroSection.jsx, frontend_web/audioscholar-app/src/components/RecordingData.jsx, frontend_web/audioscholar-app/src/components/RecordingList.jsx, frontend_web/audioscholar-app/src/components/SignIn.jsx, frontend_web/audioscholar-app/src/components/SignUp.jsx, frontend_web/audioscholar-app/src/components/Uploading.jsx, frontend_web/audioscholar-app/src/components/UserProfile.jsx, frontend_web/audioscholar-app/src/components/UserProfileEdit.jsx, frontend_web/audioscholar-app/src/components/dashboard.jsx, frontend_web/audioscholar-app/src/components/footer.jsx, frontend_web/audioscholar-app/src/components/header.jsx, frontend_web/audioscholar-app/src/components/pricing.jsx, frontend_web/audioscholar-app/src/components/testimonials.jsx, frontend_web/audioscholar-app/src/index.css, frontend_web/audioscholar-app/tailwind.config.js
- Modified `index.html` to enhance favicon support and update the title to "AudioScholar".
- Refactored `tailwind.config.js` to use ES module syntax.
- Updated `App.jsx` to streamline component imports and improve route organization.
- Enhanced `Dashboard.jsx` with a new title and adjusted layout for better user experience.
- Refined `Footer.jsx` to improve layout and ensure consistent branding.
- Updated `GithubAuthCallback.jsx` to include a title for better user feedback during login.
- Improved `Header.jsx` for better navigation and layout consistency.
- Refactored `HeroSection.jsx` for improved readability and structure.
- Updated `UserProfile.jsx` and `UserProfileEdit.jsx` for better state management and user experience.
- Enhanced `Uploading.jsx` to improve form handling and user …
=> refactor: Update frontend structure and components for AudioScholar

backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AuthController.java, frontend_web/audioscholar-app/src/config/firebaseConfig.js, frontend_web/audioscholar-app/src/pages/Auth/SignIn/SignIn.jsx, frontend_web/audioscholar-app/src/pages/Upload/Uploading.jsx, frontend_web/audioscholar-app/src/services/authService.js
- Updated `AuthController.java` to improve Firebase token verification and user record fetching, including better logging for debugging.
- Added `verifyGoogleTokenWithBackend` function in `authService.js` to handle Google ID token verification with the backend.
- Modified `SignIn.jsx` to support Google sign-in and backend verification, improving error handling and user feedback.
- Enhanced `Uploading.jsx` to prevent navigation during uploads and improve user experience with loading states.
=> refactor: Enhance authentication flow and user profile management

backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioSummarizationListenerService.java, frontend_web/audioscholar-app/src/pages/RecordingList/RecordingList.jsx
- Updated `AudioSummarizationListenerService.java` to include caching functionality for user metadata, improving performance by evicting cache entries upon processing finalization and metadata status updates.
- Modified `RecordingList.jsx` to implement polling for processing recordings, enhancing user experience by automatically refreshing the list of recordings every 15 seconds when processing is detected.
- Improved error handling in `fetchRecordings` to manage authentication and network errors more effectively, ensuring a smoother user experience during data fetching.
=> refactor: Enhance AudioSummarizationListenerService and RecordingList component

frontend_web/audioscholar-app/src/pages/RecordingData/RecordingData.jsx, frontend_web/audioscholar-app/src/styles/index.css, frontend_web/audioscholar-app/tailwind.config.js
- Implemented `handleCopySummaryAndVocab` function to copy summary details and key vocabulary to clipboard.
- Updated button in the UI to trigger the copy functionality, enhancing user experience.
- Integrated Tailwind CSS typography plugin in `tailwind.config.js` for improved text styling.
- Adjusted CSS imports to include the typography plugin in `index.css`.
=> feat: Add copy functionality for summary and vocabulary in RecordingData component

backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/TokenRevocationService.java
- Updated FirebaseService to return null instead of throwing an exception when a document is not found.
- Enhanced TokenRevocationService to handle null responses from Firestore, updating the denylist cache accordingly and improving logging for better clarity on access decisions.
=> refactor: Improve Firestore interaction handling in FirebaseService and TokenRevocationService

backend/audioscholar/src/main/java/edu/cit/audioscholar/config/WebConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/model/AudioMetadata.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioTranscriptionListenerService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/FirebaseService.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/service/PptxConversionListenerService.java
- Added audioUrl field to AudioMetadata class for improved audio file management.
- Updated FirebaseService to set audioUrl from Firestore data.
- Enhanced WebConfig with a custom ObjectMapper bean for JSON serialization settings.
- Improved logging in AudioTranscriptionListenerService for better clarity on transcription requests and conditions for summarization.
- Refactored PptxConversionListenerService to include additional checks for summarization readiness and retry logic for transcription when PDF conversion is complete.
=> feat: Enhance audio metadata handling and transcription process

backend/audioscholar/src/main/java/edu/cit/audioscholar/service/AudioProcessingService.java
- Added functionality to delete PowerPoint and generated PDF Nhost files associated with metadata.
- Implemented logging for successful and failed deletion attempts.
- Included deletion of temporary PowerPoint files to ensure proper cleanup.
=> feat: Enhance file deletion handling in AudioProcessingService

frontend_mobile/AudioScholar/.gitignore, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/dto/AudioMetadataDto.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/NetworkModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsUiState.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/library/LibraryViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml, frontend_web/audioscholar-app/src/services/authService.js
- Added audioUrl and generatedPdfUrl fields to AudioMetadataDto and RecordingDetailsUiState for improved metadata management.
- Updated RecordingDetailsScreen to display PDF availability and handle audio playback more effectively.
- Modified LibraryScreen and LibraryViewModel to support new audio and PDF URL fields.
- Adjusted MainActivity to include new arguments for audio and PDF URLs in navigation.
- Updated strings.xml with new resource strings for PDF handling and error messages.
=> feat: Enhance audio metadata handling and UI updates

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/dto/RecommendationDto.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsScreen.kt
- Introduced fallbackThumbnailUrl in RecommendationDto to enhance image loading reliability.
- Updated YouTubeRecommendationCard to utilize fallback thumbnail logic for improved user experience when the primary thumbnail fails to load.
=> feat: Add fallback thumbnail support in RecommendationDto and update UI handling

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/CardPaymentDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/EWalletPaymentDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/PaymentMethodSelectionScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/SubscriptionPricingScreen.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
- Added SubscriptionPricingScreen to display subscription plans and pricing options.
- Introduced PaymentMethodSelectionScreen for users to choose between card and e-wallet payment methods.
- Created CardPaymentDetailsScreen and EWalletPaymentDetailsScreen for handling respective payment details.
- Updated MainActivity to include new navigation routes for subscription and payment screens.
- Enhanced UserProfileScreen with a button to navigate to SubscriptionPricingScreen.
- Added necessary string resources in strings.xml for new features and UI elements.
=> feat: Implement subscription and payment screens

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/NetworkModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsUiState.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/details/RecordingDetailsViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/recording/RecordingViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/SubscriptionPricingScreen.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
- Improved confirmCancelRecording method to include state validation and logging for better debugging.
- Optimistically updated UI state before sending the cancel recording command, ensuring accurate state management.
- Refined handling of recording state to prevent unnecessary service commands when already not recording.
=> SubscriptionFeatureFix1-Frontend_Mobile-Biacolo

frontend_mobile/.idea/caches/deviceStreaming.xml, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/CardPaymentDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/EWalletPaymentDetailsScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/SubscriptionPricingScreen.kt
- Removed unnecessary state restoration in MainActivity navigation for Profile and SubscriptionPricing screens, streamlining the navigation flow.
- Updated navigation logic in CardPaymentDetailsScreen and EWalletPaymentDetailsScreen to ensure proper back stack handling.
- Cleaned up imports and optimized the UserProfileScreen layout for better readability and maintainability.
=> MinorFixesArrangement-Frontend_Mobile-Biacolo

frontend_web/audioscholar-app/src/pages/Auth/SignIn/SignIn.jsx, frontend_web/audioscholar-app/src/pages/Auth/SignUp/SignUp.jsx, frontend_web/audioscholar-app/src/pages/UserProfile/UserProfile.jsx
- Updated UserProfile component to include referrerPolicy attribute on the profile image, improving user privacy by controlling the information sent to third-party sites.
=> Implementnavigationtosign-inpageaftersuccessfulsign-up-FrontEnd-Duterte

backend/audioscholar/src/main/java/edu/cit/audioscholar/config/SecurityConfig.java, backend/audioscholar/src/main/java/edu/cit/audioscholar/controller/AuthController.java
- Added new allowed origins for CORS in SecurityConfig to support additional local development environments.
- Enhanced AuthController to conditionally set user display name and photo URL during user creation, improving user profile management.
=> feat: Update CORS configuration and enhance AuthController for user profile handling

frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/data/remote/dto/UserProfileDto.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/di/AppModule.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainActivity.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/main/MainViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/profile/UserProfileViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/PaymentViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/SubscriptionPricingScreen.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/SubscriptionViewModel.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/ui/subscription/VerificationCodeModal.kt, frontend_mobile/AudioScholar/app/src/main/java/edu/cit/audioscholar/util/PremiumStatusManager.kt, frontend_mobile/AudioScholar/app/src/main/res/values/strings.xml
- Introduced PremiumStatusManager to handle premium status logic using SharedPreferences.
- Updated UserProfileDto to include roles for better user data representation.
- Enhanced MainViewModel and UserProfileViewModel to manage and reflect premium status.
- Integrated premium status indicators in MainAppScreen and UserProfileScreen.
- Updated SubscriptionViewModel to manage subscription plans based on premium status.
- Added new string resources for premium-related UI elements.
=> feat: Enhance user premium status management and UI integration

frontend_web/audioscholar-app/src/pages/Dashboard/DashBoard.jsx, frontend_web/audioscholar-app/src/pages/RecordingData/RecordingData.jsx, frontend_web/audioscholar-app/src/pages/RecordingList/RecordingList.jsx
- Replaced the static upload logo with an icon from react-icons for a cleaner look.
- Removed the logout functionality to simplify the component's logic and focus on the dashboard features.
=> RecordingMinorFix-Frontend_Web-Biacolo
